name: Docker CI ghcr.io

on:
  push:
    branches: [ "main" ]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login -u NathanWarrick -p ${{ secrets.ORG_TOKEN }} ghcr.io
          docker build . -t ghcr.io/allhomelab/docker-testing:latest
          docker push ghcr.io/allhomelab/docker-testing:latest
